services:
  mysql:
    image: mysql:8.0
    container_name: lab2-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lab2_books
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-api
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root_user
      DB_PASSWORD: root
      DB_NAME: lab2_books
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
