ALTER TABLE books
    ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) NOT NULL DEFAULT 0.01,
    ADD COLUMN IF NOT EXISTS pages INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 1) NOT NULL DEFAULT 0.0;
